version: '3'

services:
  keycloak:
    image: ambient/keycloak:18.0.0.1
    ports:
      - 443:443
      - 1111:1111
    volumes:
      - ./config.env:/opt/keycloak/conf/config.env
      - ./cert.jks:/opt/keycloak/conf/cert.jks
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    volumes:
      - './pgsql:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'pgowner'
      POSTGRES_PASSWORD: 'pgowner'